### ISSUE TITLE
Add employee model

### ISSUE THREAD

**Issue by manpikingillz** [manpikingillz/fedhr-graphene-backend#3]
Add initial employee model, just to get started

**Comment by emompi** [comment]
Hi! Can I contribute on this issue?

**Comment by manpikingillz** [comment]
> Hi! Can I contribute on this issue?

Yeah sure. Though, this issue was mainly to spin a simplified Employee model to just see graphene working. There is another issue though for updating this model to have the fields needed. Would you like to take up that instead? It's this one https://github.com/manpikingillz/fedhr-graphene-backend/issues/6

If you decided to take up this issue, let me know how your proposed `Employee` model would look like

**Comment by manpikingillz** [comment]
@emompi I will go ahead and close this issue since the PR is already merged. Take a look at https://github.com/manpikingillz/fedhr-graphene-backend/issues/6 as in the comment above.
